// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function MakeRequest(arg1) {
  return window['go']['request']['Request']['MakeRequest'](arg1);
}

export function StartUp(arg1) {
  return window['go']['request']['Request']['StartUp'](arg1);
}
